import { RiskRule } from "./risk.types";

export const riskRules: RiskRule[] = [
  {
    id: "rr-web-search",
    tool: "google-search",
    action: "search",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-git-branch",
    tool: "github",
    action: "create_branch",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-git-commit",
    tool: "github",
    action: "create_commit",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-git-pr",
    tool: "github",
    action: "create_pull_request",
    baseRisk: "MEDIUM",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-git-merge",
    tool: "github",
    action: "merge_pull_request",
    baseRisk: "HIGH",
    triggersApproval: true,
    destructive: false,
  },
  {
    id: "rr-db-select",
    tool: "postgresql",
    action: "select",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-db-insert",
    tool: "postgresql",
    action: "insert",
    baseRisk: "MEDIUM",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-db-update",
    tool: "postgresql",
    action: "update",
    baseRisk: "HIGH",
    triggersApproval: true,
    destructive: false,
  },
  {
    id: "rr-db-alter",
    tool: "postgresql",
    action: "alter_schema",
    baseRisk: "CRITICAL",
    triggersApproval: true,
    destructive: true,
  },
  {
    id: "rr-storage-delete",
    tool: "cloud_storage",
    action: "delete",
    baseRisk: "HIGH",
    triggersApproval: true,
    destructive: true,
  },
  {
    id: "rr-slack-post",
    tool: "slack",
    action: "post_message",
    baseRisk: "MEDIUM",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-stripe-charge",
    tool: "stripe",
    action: "create_invoice",
    baseRisk: "HIGH",
    triggersApproval: true,
    destructive: false,
    spendingLimitDollars: 500,
  },
  // ---------- Code Execution Sandbox ----------
  {
    id: "rr-code-run-js",
    tool: "code-execution",
    action: "run_javascript",
    baseRisk: "MEDIUM",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-code-run-ts",
    tool: "code-execution",
    action: "run_typescript",
    baseRisk: "MEDIUM",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-code-write-temp",
    tool: "code-execution",
    action: "write_temp_file",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-code-read-temp",
    tool: "code-execution",
    action: "read_temp_file",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-code-list-temp",
    tool: "code-execution",
    action: "list_temp_files",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  // ---------- Computer Use / Browser ----------
  {
    id: "rr-cu-navigate",
    tool: "computer-use",
    action: "navigate",
    baseRisk: "MEDIUM",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-cu-click",
    tool: "computer-use",
    action: "click",
    baseRisk: "MEDIUM",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-cu-type",
    tool: "computer-use",
    action: "type",
    baseRisk: "MEDIUM",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-cu-extract",
    tool: "computer-use",
    action: "extract_text",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-cu-screenshot",
    tool: "computer-use",
    action: "screenshot",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-cu-evaluate",
    tool: "computer-use",
    action: "evaluate",
    baseRisk: "HIGH",
    triggersApproval: true,
    destructive: false,
  },
  {
    id: "rr-cu-close",
    tool: "computer-use",
    action: "close",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  // ---------- Project Writer ----------
  { id: "rr-pw-write", tool: "project-writer", action: "write_file", baseRisk: "MEDIUM", triggersApproval: false, destructive: false },
  { id: "rr-pw-read", tool: "project-writer", action: "read_file", baseRisk: "LOW", triggersApproval: false, destructive: false },
  { id: "rr-pw-list", tool: "project-writer", action: "list_files", baseRisk: "LOW", triggersApproval: false, destructive: false },
  { id: "rr-pw-append", tool: "project-writer", action: "append_file", baseRisk: "MEDIUM", triggersApproval: false, destructive: false },
  { id: "rr-pw-delete", tool: "project-writer", action: "delete_file", baseRisk: "HIGH", triggersApproval: true, destructive: true },
  { id: "rr-pw-mkdir", tool: "project-writer", action: "create_directory", baseRisk: "LOW", triggersApproval: false, destructive: false },
];
