import { RiskRule } from "./risk.types";

export const riskRules: RiskRule[] = [
  {
    id: "rr-web-search",
    tool: "google-search",
    action: "search",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-git-branch",
    tool: "github",
    action: "create_branch",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-git-commit",
    tool: "github",
    action: "create_commit",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-git-pr",
    tool: "github",
    action: "create_pull_request",
    baseRisk: "MEDIUM",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-git-merge",
    tool: "github",
    action: "merge_pull_request",
    baseRisk: "HIGH",
    triggersApproval: true,
    destructive: false,
  },
  {
    id: "rr-db-select",
    tool: "postgresql",
    action: "select",
    baseRisk: "LOW",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-db-insert",
    tool: "postgresql",
    action: "insert",
    baseRisk: "MEDIUM",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-db-update",
    tool: "postgresql",
    action: "update",
    baseRisk: "HIGH",
    triggersApproval: true,
    destructive: false,
  },
  {
    id: "rr-db-alter",
    tool: "postgresql",
    action: "alter_schema",
    baseRisk: "CRITICAL",
    triggersApproval: true,
    destructive: true,
  },
  {
    id: "rr-storage-delete",
    tool: "cloud_storage",
    action: "delete",
    baseRisk: "HIGH",
    triggersApproval: true,
    destructive: true,
  },
  {
    id: "rr-slack-post",
    tool: "slack",
    action: "post_message",
    baseRisk: "MEDIUM",
    triggersApproval: false,
    destructive: false,
  },
  {
    id: "rr-stripe-charge",
    tool: "stripe",
    action: "create_invoice",
    baseRisk: "HIGH",
    triggersApproval: true,
    destructive: false,
    spendingLimitDollars: 500,
  }
];
