import { BaseAdapter, ToolExecutionContext, ToolExecutionContract } from "./base.adapter";
import * as fs from "node:fs";
import * as path from "node:path";
import { randomUUID } from "node:crypto";

/**
 * Project Writer Adapter
 * Allows agents to create and modify real source files inside a controlled workspace.
 * This is the foundation for "write its own code and build its own files".
 */
export class ProjectWriterAdapter extends BaseAdapter {
  get provider(): string {
    return "project-writer";
  }

  // Only these roots are allowed (safety boundary)
  private readonly allowedRoots = [
    path.join(process.cwd(), "generated"),           // preferred safe area
    path.join(process.cwd(), "src", "generated"),
    path.join(process.cwd(), "apps", "generated"),
    path.join(process.cwd(), ".rufflo-sandbox"),
  ];

  async execute(context: ToolExecutionContext): Promise<ToolExecutionContract> {
    const start = Date.now();
    const correlationId = context.correlationId || randomUUID();
    const { action, parameters } = context;

    try {
      switch (action) {
        case "write_file":
          return this.writeFile(parameters, start, correlationId);
        case "read_file":
          return this.readFile(parameters, start, correlationId);
        case "list_files":
          return this.listFiles(parameters, start, correlationId);
        case "append_file":
          return this.appendFile(parameters, start, correlationId);
        case "delete_file":
          return this.deleteFile(parameters, start, correlationId);
        case "create_directory":
          return this.createDirectory(parameters, start, correlationId);
        default:
          throw new Error(`Unsupported project-writer action: ${action}`);
      }
    } catch (err: any) {
      return this.createResponse(
        false,
        action,
        null,
        err.message || String(err),
        Date.now() - start,
        correlationId,
        "HIGH"
      );
    }
  }

  private resolveSafePath(relativePath: string): string {
    if (!relativePath || relativePath.includes("..")) {
      throw new Error("Invalid path: path traversal is not allowed");
    }

    // Force everything under /generated by default if no root given
    let target = relativePath;
    if (!path.isAbsolute(relativePath)) {
      target = path.join(process.cwd(), "generated", relativePath);
    }

    const resolved = path.resolve(target);

    const isAllowed = this.allowedRoots.some((root) => {
      const resolvedRoot = path.resolve(root);
      return resolved === resolvedRoot || resolved.startsWith(resolvedRoot + path.sep);
    });

    if (!isAllowed) {
      throw new Error(
        `Security Violation: Writing outside allowed project roots is forbidden. Attempted: ${resolved}`
      );
    }

    return resolved;
  }

  private writeFile(parameters: any, start: number, correlationId: string) {
    const relativePath = parameters.path || parameters.filename;
    const content = parameters.content;

    if (!relativePath) throw new Error("Parameter 'path' is required");
    if (content === undefined || content === null) {
      throw new Error("Parameter 'content' is required");
    }

    const fullPath = this.resolveSafePath(relativePath);
    const dir = path.dirname(fullPath);

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(fullPath, String(content), "utf8");

    return this.createResponse(
      true,
      "write_file",
      {
        path: fullPath,
        relativePath,
        bytes: Buffer.byteLength(String(content)),
        created: true,
      },
      null,
      Date.now() - start,
      correlationId,
      "MEDIUM"
    );
  }

  private appendFile(parameters: any, start: number, correlationId: string) {
    const relativePath = parameters.path || parameters.filename;
    const content = parameters.content;
    if (!relativePath) throw new Error("Parameter 'path' is required");
    if (content === undefined) throw new Error("Parameter 'content' is required");

    const fullPath = this.resolveSafePath(relativePath);
    fs.appendFileSync(fullPath, String(content), "utf8");

    return this.createResponse(
      true,
      "append_file",
      { path: fullPath, appendedBytes: Buffer.byteLength(String(content)) },
      null,
      Date.now() - start,
      correlationId,
      "MEDIUM"
    );
  }

  private readFile(parameters: any, start: number, correlationId: string) {
    const relativePath = parameters.path || parameters.filename;
    if (!relativePath) throw new Error("Parameter 'path' is required");

    const fullPath = this.resolveSafePath(relativePath);
    if (!fs.existsSync(fullPath)) {
      throw new Error(`File not found: ${relativePath}`);
    }

    const content = fs.readFileSync(fullPath, "utf8");
    return this.createResponse(
      true,
      "read_file",
      { path: fullPath, content, size: content.length },
      null,
      Date.now() - start,
      correlationId,
      "LOW"
    );
  }

  private listFiles(parameters: any, start: number, correlationId: string) {
    const relativePath = parameters.path || ".";
    const fullPath = this.resolveSafePath(relativePath);

    if (!fs.existsSync(fullPath)) {
      return this.createResponse(
        true,
        "list_files",
        { path: fullPath, files: [] },
        null,
        Date.now() - start,
        correlationId,
        "LOW"
      );
    }

    const entries = fs.readdirSync(fullPath, { withFileTypes: true }).map((e) => ({
      name: e.name,
      type: e.isDirectory() ? "directory" : "file",
    }));

    return this.createResponse(
      true,
      "list_files",
      { path: fullPath, files: entries },
      null,
      Date.now() - start,
      correlationId,
      "LOW"
    );
  }

  private deleteFile(parameters: any, start: number, correlationId: string) {
    const relativePath = parameters.path || parameters.filename;
    if (!relativePath) throw new Error("Parameter 'path' is required");

    const fullPath = this.resolveSafePath(relativePath);
    if (fs.existsSync(fullPath)) {
      fs.unlinkSync(fullPath);
    }

    return this.createResponse(
      true,
      "delete_file",
      { path: fullPath, deleted: true },
      null,
      Date.now() - start,
      correlationId,
      "HIGH"
    );
  }

  private createDirectory(parameters: any, start: number, correlationId: string) {
    const relativePath = parameters.path;
    if (!relativePath) throw new Error("Parameter 'path' is required");

    const fullPath = this.resolveSafePath(relativePath);
    fs.mkdirSync(fullPath, { recursive: true });

    return this.createResponse(
      true,
      "create_directory",
      { path: fullPath, created: true },
      null,
      Date.now() - start,
      correlationId,
      "LOW"
    );
  }
}
