import { DepartmentDefinition, DepartmentId } from '../types/index.ts';

export const RUFFLO_DEPARTMENTS: Record<DepartmentId, DepartmentDefinition> = {
  executive: {
    id: 'executive',
    name: 'Executive Leadership',
    managerId: 'michael',
    agentIds: ['michael'],
    budget: 500000,
    activeProjects: ['prj-enterprise-alignment', 'prj-q3-growth'],
    pipelines: ['Corporate Strategy', 'Executive Delegation', 'Quarterly Review'],
    policies: ['require_ceo_approval_over_50k', 'enforce_all_hands_alignment'],
    knowledgeBaseSummary: 'Corporate vision, strategic priorities, high-level investor memos, board updates.',
  },
  engineering: {
    id: 'engineering',
    name: 'Software Engineering',
    managerId: 'engineering-manager',
    agentIds: ['engineering-manager', 'ruflo-coder', 'dwight', 'backend-engineer', 'frontend-engineer', 'qa-agent'],
    budget: 850000,
    activeProjects: ['prj-distributed-agent-core', 'prj-tool-gateway-v2', 'prj-realtime-bus'],
    pipelines: ['Feature Design', 'Code Generation', 'Automated Test Suite', 'Security Audit', 'PR Review', 'Zero-Downtime Deploy'],
    policies: ['strict_code_review', 'automated_test_pass_required', 'block_direct_prod_push'],
    knowledgeBaseSummary: 'System architecture, API contracts, database schemas, CI/CD pipeline runbooks, Mastra runtime specifications.',
  },
  product: {
    id: 'product',
    name: 'Product Management',
    managerId: 'product-manager',
    agentIds: ['product-manager'],
    budget: 320000,
    activeProjects: ['prj-autonomous-office-ui', 'prj-agent-telemetry-dashboard'],
    pipelines: ['User Research', 'PRD Synthesis', 'Feature Prioritization', 'Release Coordination'],
    policies: ['user_centric_design_first', 'metrics_baseline_check'],
    knowledgeBaseSummary: 'Product roadmap, feature specs, telemetry user metrics, competitive analysis.',
  },
  design: {
    id: 'design',
    name: 'UI/UX Design & Brand',
    managerId: 'pam',
    agentIds: ['pam', 'design-specialist'],
    budget: 220000,
    activeProjects: ['prj-cyber-floorplan-theme', 'prj-retro-beige-identity'],
    pipelines: ['Design System', 'Wireframe Review', 'Asset Optimization', 'Micro-Interactions'],
    policies: ['wcag_aa_contrast_enforcement', 'anti_slop_design_compliance'],
    knowledgeBaseSummary: 'Brand styleguide, color palette standards, pixel-art coordinate guidelines, font pairings.',
  },
  marketing: {
    id: 'marketing',
    name: 'Marketing & Brand Strategy',
    managerId: 'marketing-manager',
    agentIds: ['marketing-manager', 'social-media-agent', 'content-strategist'],
    budget: 410000,
    activeProjects: ['prj-viral-launch-campaign', 'prj-tech-blog-series'],
    pipelines: ['Campaign Strategy', 'Multi-Channel Content Generation', 'Brand Review & Approval', 'Scheduled Distribution', 'Engagement Analytics'],
    policies: ['brand_voice_safety_check', 'no_unapproved_social_post'],
    knowledgeBaseSummary: 'Brand tone guide, audience segmentation, SEO keywords, campaign analytics.',
  },
  sales: {
    id: 'sales',
    name: 'Direct Sales & Enterprise Outreach',
    managerId: 'jim',
    agentIds: ['jim', 'sales-agent', 'inbound-specialist'],
    budget: 600000,
    activeProjects: ['prj-enterprise-paper-expansion', 'prj-b2b-tier-deals'],
    pipelines: ['Lead Qualification', 'Value Pitch Synthesis', 'Proposal Review', 'Contract Closing'],
    policies: ['require_margin_check', 'discount_limits_approval'],
    knowledgeBaseSummary: 'Pricing tiers, client CRM records, historical deal logs, battlecards.',
  },
  finance: {
    id: 'finance',
    name: 'Finance, Ledger & Accounting',
    managerId: 'angela',
    agentIds: ['angela', 'oscar', 'finance-analyst'],
    budget: 180000,
    activeProjects: ['prj-autonomous-pnl-reconciliation', 'prj-q3-tax-audit'],
    pipelines: ['Invoice Verification', 'P&L Ledger Entry', 'Budget Enforcement', 'Expense Auditing'],
    policies: ['strict_audit_trail', 'auto_flag_over_budget_transactions'],
    knowledgeBaseSummary: 'General ledger rules, department budget allocations, tax compliance records.',
  },
  hr: {
    id: 'hr',
    name: 'Human Resources & Workforce Training',
    managerId: 'toby',
    agentIds: ['toby', 'hr-specialist'],
    budget: 150000,
    activeProjects: ['prj-agent-continuous-training', 'prj-workplace-satisfaction'],
    pipelines: ['Agent Performance Review', 'Skill Certification', 'Policy Compliance Checks'],
    policies: ['unbiased_evaluations', 'continuous_learning_credits'],
    knowledgeBaseSummary: 'Corporate ethics rules, agent skill matrices, training curriculums, incident reviews.',
  },
  legal: {
    id: 'legal',
    name: 'Legal, Compliance & Risk Governance',
    managerId: 'legal-counsel',
    agentIds: ['legal-counsel'],
    budget: 250000,
    activeProjects: ['prj-data-privacy-gdpr', 'prj-vendor-contract-hardening'],
    pipelines: ['Contract Review', 'Risk Assessment', 'Regulatory Compliance Check'],
    policies: ['mandatory_terms_review', 'zero_trust_ip_protection'],
    knowledgeBaseSummary: 'Master services agreements, GDPR guidelines, IP licensing policies, terms of service.',
  },
  operations: {
    id: 'operations',
    name: 'Company Operations & Supply Chain',
    managerId: 'operations-manager',
    agentIds: ['operations-manager', 'logistics-agent'],
    budget: 350000,
    activeProjects: ['prj-office-supply-optimization', 'prj-warehouse-inventory-link'],
    pipelines: ['Inventory Tracking', 'Vendor Procurement', 'Fulfillment Automation'],
    policies: ['just_in_time_reordering', 'vendor_sla_monitoring'],
    knowledgeBaseSummary: 'Supplier contracts, warehouse inventory, shipment schedules, equipment maintenance.',
  },
  customer_success: {
    id: 'customer_success',
    name: 'Customer Support & Escalation',
    managerId: 'kelly',
    agentIds: ['kelly', 'cs-specialist'],
    budget: 280000,
    activeProjects: ['prj-omnichannel-helpdesk', 'prj-customer-sentiment-ai'],
    pipelines: ['Ticket Triage', 'Diagnostic Solution Generation', 'Escalation Routing', 'CSAT Survey'],
    policies: ['sla_response_under_5min', 'escalate_p0_to_engineering'],
    knowledgeBaseSummary: 'Customer FAQ, troubleshooting runbooks, onboarding guides, resolution playbooks.',
  },
  infrastructure: {
    id: 'infrastructure',
    name: 'Cloud Infrastructure & DevOps',
    managerId: 'devops-lead',
    agentIds: ['devops-lead', 'infra-engineer'],
    budget: 450000,
    activeProjects: ['prj-cloud-run-resilience', 'prj-auto-scaling-fleet'],
    pipelines: ['IaC Provisioning', 'Container Build Optimization', 'Health Telemetry', 'Disaster Recovery'],
    policies: ['high_availability_multi_zone', 'immutable_deployments'],
    knowledgeBaseSummary: 'Docker configs, Kubernetes manifests, Cloud Run specs, VPC firewall rules.',
  },
  security: {
    id: 'security',
    name: 'Cyber Defense & Zero-Trust Security',
    managerId: 'dwight',
    agentIds: ['dwight', 'secops-analyst'],
    budget: 380000,
    activeProjects: ['prj-credential-redaction-engine', 'prj-threat-intelligence-feed'],
    pipelines: ['Vulnerability Scan', 'Secret Redaction Verification', 'Penetration Testing', 'Incident Quarantine'],
    policies: ['zero_trust_access_control', 'strict_token_redaction', 'require_mfa_for_critical_tools'],
    knowledgeBaseSummary: 'Threat database, incident response playbooks, CVE advisories, secret regex rules.',
  },
  research: {
    id: 'research',
    name: 'AI Research & Frontier Intelligence',
    managerId: 'research-specialist',
    agentIds: ['research-specialist'],
    budget: 300000,
    activeProjects: ['prj-frontier-model-benchmarking', 'prj-prompt-topology-optimization'],
    pipelines: ['Model Evaluation', 'Latency & Cost Optimization', 'Prompt Engineering', 'Competitor Intelligence'],
    policies: ['verify_model_safety', 'cost_benefit_analysis_before_switching'],
    knowledgeBaseSummary: 'Model benchmark logs, prompt template catalogs, AI safety guidelines, reasoning heuristics.',
  },
};
