import { repositoryInspector, type RepoStructure, type DiffReview } from "../../knowledge/repository-inspector.ts";
import { autonomousLifecycle, type AutonomousDevelopmentResult } from "../../core/autonomy/autonomous-lifecycle.ts";
import { Octokit } from "@octokit/rest";

export interface RepositoryTask {
  id: string;
  agentId: string;
  organizationId: string;
  workspace: string;
  objective: string;
  branchName?: string;
  githubRepo?: {
    owner: string;
    repo: string;
    baseBranch?: string;
  };
  maxAttempts?: number;
  timeoutMs?: number;
}

export interface RepositoryFeatureResult {
  taskId: string;
  success: boolean;
  structure: RepoStructure;
  development: AutonomousDevelopmentResult;
  diff: DiffReview;
  pullRequestUrl?: string;
  summary: string;
}

export class RepositoryEngineer {
  async develop(task: RepositoryTask): Promise<RepositoryFeatureResult> {
    const workspace = task.workspace || process.cwd();
    const branchName = task.branchName || `feature/rufflo-${Date.now()}`;

    // 1. Inspect repository architecture
    const structure = repositoryInspector.inspect(workspace);

    // 2. Execute autonomous development loop (Inspect -> Implement -> Test -> Security -> Evaluate -> Learn)
    const development = await autonomousLifecycle.run({
      id: task.id,
      agentId: task.agentId,
      organizationId: task.organizationId,
      objective: task.objective,
      workspace,
      maxAttempts: task.maxAttempts ?? 5,
      timeoutMs: task.timeoutMs ?? 180_000,
      requiredCapability: "repository-engineering",
    });

    // 3. Inspect git diff & security review of changes
    const diff = repositoryInspector.getDiff(workspace);

    // 4. Optionally create GitHub Pull Request if GitHub token & repo provided
    let pullRequestUrl: string | undefined = undefined;

    if (task.githubRepo && process.env.GITHUB_TOKEN && development.success) {
      try {
        const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
        const { owner, repo, baseBranch = "main" } = task.githubRepo;

        // Create Pull Request
        const pr = await octokit.rest.pulls.create({
          owner,
          repo,
          title: `🤖 Autonomous Feature: ${task.objective.slice(0, 60)}`,
          head: branchName,
          base: baseBranch,
          body: `## 🤖 Rufflo Autonomous Repository Engineer\n\n### Objective\n${task.objective}\n\n### Verification Summary\n- **Status**: ${development.stage}\n- **Attempts**: ${development.attempts}\n- **Diff Summary**: ${diff.summary}\n\n### Security Audit\n${
            diff.securityWarnings.length === 0
              ? "✅ No hardcoded secrets or unsafe evaluation functions detected."
              : diff.securityWarnings.map(w => `- ⚠️ ${w}`).join("\n")
          }\n\n*Generated by Rufflo Autonomous Agent Loop.*`,
        });

        pullRequestUrl = pr.data.html_url;
      } catch (err: any) {
        console.warn("Pull request creation skipped or failed:", err.message);
      }
    }

    const summary = development.success
      ? `Successfully developed feature in ${diff.files.length} files (${diff.summary}).`
      : `Feature development failed at stage ${development.stage}: ${development.failure || "Unresolved issues"}`;

    return {
      taskId: task.id,
      success: development.success && diff.securityWarnings.length === 0,
      structure,
      development,
      diff,
      pullRequestUrl,
      summary,
    };
  }
}

export const repositoryEngineer = new RepositoryEngineer();
