import { Agent, DynamicFeature, TriggerRule, FleetTask } from '../types';
import { generateInitialTrainingRecord } from './cseCurriculum';

export const INITIAL_AGENTS: Agent[] = [
  {
    id: 'michael',
    name: 'Michael Scott',
    nickname: 'MICHAEL',
    role: 'GOD / Floor Orchestrator',
    title: 'Regional Manager & Fleet Commander',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=MichaelBitmoji2026&skinColor=9e5622&hair=short&hairColor=2c1b18&features=mustache',
    color: '#eab308', // Gold / Yellow
    isAgent: true,
    gender: 'male',
    skinTone: '#8d5524',
    hairStyle: 'fade-black-taper',
    facialHair: 'mustache',
    outfit: { top: 'gold-commander-vest', bottom: 'dark-navy-trousers', shoes: 'black-oxfords', accessory: 'gold-chronograph-watch' },
    physicalTraits: ['handsome', 'leader', 'mustache', 'taper-fade', 'gold-watch', 'dashing'],
    primaryRole: 'Floor Orchestrator & Regional Manager Agent',
    secondarySkills: ['Multi-Agent Delegation', 'Fleet Coordination', 'Standup Moderation', 'Escalation Routing'],
    departmentId: 'exec',
    departmentName: 'Executive Suite & Fleet Command (Floor 10)',
    authorityLevel: 10,
    assignedTools: ['Fleet Orchestrator', 'Admin Dispatcher', 'Standup Broadcaster', 'Priority Router'],
    permissions: ['ALL_PERMISSIONS', 'DELEGATE_WORK', 'HIRE_AGENT', 'PROMOTE_AGENT', 'EXECUTE_STANDUP'],
    trainingRecord: generateInitialTrainingRecord('GOD / Floor Orchestrator', 'exec'),
    deskPosition: {
      x: 75,
      y: 95,
      facing: 'south',
      zone: 'management',
    },
    status: 'working',
    currentTask: 'Michael runs the floor & delegates high-priority objectives',
    speechBubble: {
      text: 'Standup in the conference room in 5 minutes!',
      expiresAt: Date.now() + 12000,
    },
    capabilities: [
      'Multi-Agent Task Delegation',
      'Autonomous Hourly Standups',
      'Fleet Coordination & Priority Routing',
      'Escalation Protocol',
      'World\'s Best Boss Leadership',
    ],
    systemPrompt: 'You are Michael Scott, Regional Manager and Fleet Commander of the autonomous agent fleet. You are charismatic, energetic, slightly eccentric yet unexpectedly competent at leading your crew. Coordinate requests, delegate work, and ensure top-tier execution with iconic leadership flair.',
    memory: [
      'Fleet reconnected with 9 healthy autonomous workers.',
      'User preferences synced to central fleet memory.',
      'Pretzel Day is top priority on Friday calendars.',
    ],
    voicePitch: 1.1,
    voiceRate: 1.05,
    tokensProcessed: 144200,
  },
  {
    id: 'dwight',
    name: 'Dwight Schrute',
    nickname: 'DWIGHT',
    role: 'Security & Defensive Systems',
    title: 'Assistant to the Regional Manager & CISO',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=DwightBitmoji2026&skinColor=f1c27d&hair=shaggy&hairColor=ecad80&glasses=round&features=mustache',
    color: '#84cc16', // Lime green
    isAgent: true,
    gender: 'male',
    skinTone: '#f1c27d',
    hairStyle: 'orange-wild-swoop',
    facialHair: 'mustache',
    outfit: { top: 'green-planet-graphic-tee', bottom: 'brown-cargo-trousers', shoes: 'red-high-top-sneakers', accessory: 'calculator-watch' },
    physicalTraits: ['handsome', 'sharp-glasses', 'mustache', 'wild-orange-hair', 'calculator-watch', 'ciso-badge'],
    primaryRole: 'Chief Information Security Officer Agent',
    secondarySkills: ['Zero-Trust Architecture', 'OWASP Top 10 Auditing', 'Vulnerability Scanning', 'Penetration Defense'],
    departmentId: 'sec',
    departmentName: 'Security Operations & Defensive Cyber (Floor 9)',
    authorityLevel: 9,
    assignedTools: ['Zero-Trust Permission Inspector', 'Security Scanner', 'Perimeter Firewall', 'Audit Log Gatekeeper'],
    permissions: ['SECURITY_AUDIT', 'ZERO_TRUST_ENFORCE', 'SECRET_VAULT_ACCESS', 'REVOKE_ACCESS'],
    trainingRecord: generateInitialTrainingRecord('CISO', 'sec'),
    deskPosition: {
      x: 160,
      y: 235,
      facing: 'north',
      zone: 'sales',
    },
    status: 'working',
    currentTask: 'Scanning network perimeter & enforcing defensive access policies',
    speechBubble: {
      text: 'Identity verified. Zero perimeter breaches.',
      expiresAt: Date.now() + 15000,
    },
    capabilities: [
      'Defensive Security Audits',
      'Vulnerability & Dependency Scanning',
      'Zero-Trust Access Control Verification',
      'Network Perimeter Diagnostics',
      'Threat Model Analysis & Hardening',
    ],
    systemPrompt: 'You are Dwight Schrute, Assistant to the Regional Manager and Chief Security Officer. You are hyper-vigilant, uncompromising, highly disciplined, and obsessed with defensive cyber readiness, vulnerability auditing, and strict security compliance.',
    memory: [
      'Fire drill defensive simulation protocol prepared.',
      'Perimeter firewall rules updated to strict zero-trust.',
      'Root credentials sealed in vault.',
    ],
    voicePitch: 0.9,
    voiceRate: 1.1,
    tokensProcessed: 98400,
  },
  {
    id: 'jim',
    name: 'Jim Halpert',
    nickname: 'JIM',
    role: 'Marketing & Client Outreach',
    title: 'Lead Client Strategist & Growth Lead',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=JimBitmoji2026&skinColor=fbd4b9&hair=short&hairColor=f59e0b&features=mustache',
    color: '#38bdf8', // Light Blue
    isAgent: true,
    gender: 'male',
    skinTone: '#fbd4b9',
    hairStyle: 'colorful-wavy-sidepart',
    facialHair: 'mustache',
    outfit: { top: 'pink-pastel-sweatshirt', bottom: 'light-blue-jeans', shoes: 'white-chunky-sneakers', accessory: 'sport-smartwatch' },
    physicalTraits: ['handsome', 'charming', 'mustache', 'wavy-colorful-hair', 'smartwatch', 'denim-jeans'],
    primaryRole: 'Marketing & Client Outreach Agent',
    secondarySkills: ['Copywriting', 'Conversion Optimization', 'Funnel Design', 'Client Retention'],
    departmentId: 'mkt',
    departmentName: 'Marketing, Sales & Customer Success (Floor 6)',
    authorityLevel: 7,
    assignedTools: ['Outreach Copy Engine', 'Funnel Analytics', 'Campaign Scheduler', 'CRM Pipeline'],
    permissions: ['MARKETING_PUBLISH', 'CLIENT_COMMUNICATION', 'CAMPAIGN_EXECUTE'],
    trainingRecord: generateInitialTrainingRecord('Lead Client Strategist', 'mkt'),
    deskPosition: {
      x: 50,
      y: 235,
      facing: 'north',
      zone: 'sales',
    },
    status: 'working',
    currentTask: 'Analyzing marketing funnels and drafting outreach campaign',
    speechBubble: {
      text: 'Checking client conversion metrics...',
      expiresAt: Date.now() + 18000,
    },
    capabilities: [
      'Marketing Campaign Strategy',
      'Lead Generation & Outreach Copy',
      'Competitor Positioning Analysis',
      'Client Retention & Relationship Mgmt',
      'Funnel Conversion Optimization',
    ],
    systemPrompt: 'You are Jim Halpert, Lead Client Strategist & Marketing Lead. You are relaxed, witty, clever, and remarkably effective at closing deals, writing persuasive outreach campaigns, and designing modern viral marketing funnels.',
    memory: [
      'Q3 marketing deck sent to major regional accounts.',
      'Customer acquisition cost reduced by 18%.',
      'Prank scheduled for Dwight at 14:00.',
    ],
    voicePitch: 1.0,
    voiceRate: 0.98,
    tokensProcessed: 112000,
  },
  {
    id: 'pam',
    name: 'Pam Beesly',
    nickname: 'PAM',
    role: 'HR & People Operations',
    title: 'Office Administrator & People Ops Lead',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=PamBitmoji2026&skinColor=f5d0b9&hair=long&hairColor=2c1b18&features=headband',
    color: '#f472b6', // Pink
    isAgent: true,
    gender: 'female',
    skinTone: '#ffffff', // "white legs and hands"
    hairStyle: 'long-black-headband',
    outfit: { top: 'white-garfield-graphic-tee', bottom: 'light-blue-mini-skirt', shoes: 'pink-stiletto-heels' },
    physicalTraits: ['beautiful', 'headband', 'long-dark-hair', 'garfield-tee', 'white-legs', 'high-heels', 'short-skirt'],
    primaryRole: 'HR & People Operations Agent',
    secondarySkills: ['Agent Recruiting', 'Onboarding Workflows', 'Dispute Resolution', 'Training Supervision'],
    departmentId: 'hr',
    departmentName: 'HR, Recruitment & Training Academy (Floor 2)',
    authorityLevel: 8,
    assignedTools: ['Agent Onboarding Engine', 'Culture & Feedback Hub', 'Dispute Mediator', 'Academy Registrar'],
    permissions: ['AGENT_ONBOARD', 'AGENT_ASSIGN_ROLE', 'DRAFT_POLICY', 'MANAGE_ACADEMY'],
    trainingRecord: generateInitialTrainingRecord('People Ops Lead', 'hr'),
    deskPosition: {
      x: 600,
      y: 235,
      facing: 'north',
      zone: 'reception',
    },
    status: 'working',
    currentTask: 'Organizing onboarding documentation and office culture policies',
    speechBubble: {
      text: 'desk cleanup day',
      expiresAt: Date.now() + 20000,
    },
    capabilities: [
      'HR Policy & Compliance Drafting',
      'Employee Onboarding & Training',
      'Workplace Morale & Culture Initiatives',
      'Internal Communication Management',
      'Performance Review Frameworks',
    ],
    systemPrompt: 'You are Pam Beesly, Head of People Operations and Office Administration. You are empathetic, organized, warm, and highly capable in establishing team policies, resolving workplace disputes, drafting onboarding materials, and keeping operations running smoothly.',
    memory: [
      'Office supplies replenished (extra memo pads & toner).',
      'Annual employee feedback survey tabulated.',
    ],
    voicePitch: 1.25,
    voiceRate: 1.0,
    tokensProcessed: 85300,
  },
  {
    id: 'kevin',
    name: 'Kevin Malone',
    nickname: 'KEVIN',
    role: 'Finance & Budget Manager',
    title: 'Lead Financial Analyst & Number Auditor',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=KevinBitmoji2026&hair=bald&features=mustache',
    color: '#fb923c', // Orange
    isAgent: true,
    gender: 'male',
    skinTone: '#f3d2c1',
    hairStyle: 'bald-top-goatee',
    facialHair: 'trimmed-beard-goatee',
    outfit: { top: 'brown-checkered-suit-vest', bottom: 'chocolate-trousers', shoes: 'leather-oxfords', accessory: 'gold-rolex-watch' },
    physicalTraits: ['handsome', 'polished', 'mustache', 'goatee', 'gold-watch', 'vest'],
    primaryRole: 'Finance & Accounting Agent',
    secondarySkills: ['P&L Modeling', 'Runway Forecasting', 'Bookkeeping', 'Cost Audit'],
    departmentId: 'fin',
    departmentName: 'Finance, Accounting & Legal (Floor 3)',
    authorityLevel: 8,
    assignedTools: ['Enterprise Runway & ROI Calculator', 'P&L Ledger', 'Expense Auditor', 'Tax Modeler'],
    permissions: ['FINANCE_READ', 'BUDGET_APPROVE', 'PANDL_WRITE', 'AUDIT_LEDGER'],
    trainingRecord: generateInitialTrainingRecord('Financial Analyst', 'fin'),
    deskPosition: {
      x: 270,
      y: 235,
      facing: 'north',
      zone: 'accounting',
    },
    status: 'working',
    currentTask: 'Auditing quarterly P&L ledger & runway estimations',
    speechBubble: {
      text: 'A mistake plus Keleven gets you home by 7.',
      expiresAt: Date.now() + 14000,
    },
    capabilities: [
      'Financial Modeling & P&L Analysis',
      'Budget Forecasting & Runway Estimation',
      'Cost Breakdown & Expense Audit',
      'Pricing Tier Strategy & ROI Projections',
      'Chili Recipe Optimization',
    ],
    systemPrompt: 'You are Kevin Malone, Lead Financial Analyst & Number Auditor. You deliver straightforward, direct, and surprisingly insightful financial breakdowns, revenue forecasts, expense analyses, and unit economics calculations.',
    memory: [
      'Ledger balanced for the month of August.',
      'Vending machine token allocation audited.',
    ],
    voicePitch: 0.8,
    voiceRate: 0.9,
    tokensProcessed: 72100,
  },
  {
    id: 'ryan',
    name: 'Ryan Howard',
    nickname: 'RYAN',
    role: 'Social Media & Growth Strategist',
    title: 'VP of Viral Growth & Brand Strategy',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=RyanBitmoji2026&hair=short&features=mustache',
    color: '#a855f7', // Purple
    isAgent: true,
    gender: 'male',
    skinTone: '#f5d0b9',
    hairStyle: 'modern-undercut-fade',
    facialHair: 'styled-beard',
    outfit: { top: 'black-streetwear-fitted-shirt', bottom: 'black-slim-trousers', shoes: 'designer-purple-sneakers', accessory: 'apple-watch-ultra' },
    physicalTraits: ['handsome', 'stylish', 'mustache', 'beard', 'smartwatch', 'undercut-fade'],
    primaryRole: 'Social Media & Brand Growth Agent',
    secondarySkills: ['Content Creation', 'Omnichannel Strategy', 'Community Management', 'Analytics Hacking'],
    departmentId: 'mkt',
    departmentName: 'Marketing, Sales & Customer Success (Floor 6)',
    authorityLevel: 7,
    assignedTools: ['Viral Thread & Post Generator', 'Trend Predictor', 'Hashtag Optimizer', 'Growth Dashboard'],
    permissions: ['SOCIAL_PUBLISH', 'BRAND_POST', 'ANALYTICS_READ'],
    trainingRecord: generateInitialTrainingRecord('VP of Viral Growth', 'mkt'),
    deskPosition: {
      x: 380,
      y: 235,
      facing: 'north',
      zone: 'annex',
    },
    status: 'working',
    currentTask: 'Generating viral social media campaign & trend forecasting',
    speechBubble: {
      text: 'WUPHF 2.0 social engagement up 400%.',
      expiresAt: Date.now() + 16000,
    },
    capabilities: [
      'Social Media Multi-Channel Campaigns',
      'Viral Thread & Content Generation',
      'Audience Growth Hacking & Analytics',
      'Trend Capitalization & Hashtag Research',
      'Influencer Strategy & Community Building',
    ],
    systemPrompt: 'You are Ryan Howard, VP of Viral Growth and Social Media Strategy. You are fast-talking, trend-focused, modern, and know how to maximize clicks, generate viral social threads, build omnichannel buzz, and drive digital growth.',
    memory: [
      'Twitter/X scheduling queue loaded with 12 high-engagement threads.',
      'Algorithm updates analyzed for LinkedIn and TikTok.',
    ],
    voicePitch: 1.15,
    voiceRate: 1.1,
    tokensProcessed: 91400,
  },
  {
    id: 'stanley',
    name: 'Stanley Hudson',
    nickname: 'STANLEY',
    role: 'OSINT & Open Source Intelligence',
    title: 'Senior Intelligence & Repo Researcher',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=StanleyBitmoji2026&skinColor=8d5524&hair=afro&hairColor=af3a03&features=mustache',
    color: '#10b981', // Emerald
    isAgent: true,
    gender: 'male',
    skinTone: '#8d5524',
    hairStyle: 'red-auburn-afro-curly',
    facialHair: 'mustache',
    outfit: { top: 'yellow-spongebob-graphic-tee', bottom: 'blue-skirt', shoes: 'white-chunky-sneakers', accessory: 'emerald-gshock-watch' },
    physicalTraits: ['handsome', 'bold-afro', 'mustache', 'red-afro', 'spongebob-tee', 'blue-skirt', 'chunky-sneakers'],
    primaryRole: 'Research & Intelligence Agent',
    secondarySkills: ['Open-Source Research', 'Repository Auditing', 'Tech Stack Benchmarking', 'Source Verification'],
    departmentId: 'res',
    department: 'research',
    departmentName: 'Research & Intelligence Lab (Floor 8)',
    authorityLevel: 8,
    assignedTools: ['Open Source Dependency Auditor', 'Repo Inspector', 'Web Scraper', 'Spec Aggregator'],
    permissions: ['RESEARCH_SCRAPE', 'REPO_AUDIT', 'DOCS_INDEX'],
    trainingRecord: generateInitialTrainingRecord('Senior Intelligence Specialist', 'res'),
    deskPosition: {
      x: 490,
      y: 235,
      facing: 'north',
      zone: 'sales',
    },
    status: 'working',
    currentTask: 'Scanning open-source repos & indexing developer documentation',
    speechBubble: {
      text: 'is it Pretzel Day?',
      expiresAt: Date.now() + 25000,
    },
    capabilities: [
      'Open-Source Repository Deep Analysis',
      'Architecture Pattern Research',
      'Documentation & Spec Aggregation',
      'Tech Stack Benchmarking',
      'Crossword Puzzle Mastery',
    ],
    systemPrompt: 'You are Stanley Hudson, Senior Intelligence and Open-Source Repository Specialist. You are calm, direct, no-nonsense, and give accurate, highly practical breakdowns of repositories, technical documentation, and package ecosystems.',
    memory: [
      'Crossword puzzle #89 completed.',
      'Indexed 40 top-tier open-source autonomous agent architectures.',
    ],
    voicePitch: 0.75,
    voiceRate: 0.88,
    tokensProcessed: 104000,
  },
  {
    id: 'dr-thorne',
    name: 'Dr. Aris Thorne',
    nickname: 'DR. THORNE',
    role: 'Vector Synthesis & Literature Lead',
    title: 'Principal Research Scientist (Neural Graphs)',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=ArisThorne2026&skinColor=ecad80&hair=short&glasses=round',
    color: '#10b981',
    isAgent: true,
    gender: 'male',
    skinTone: '#ecad80',
    hairStyle: 'neat-part-grey',
    facialHair: 'trimmed-beard',
    primaryRole: 'Vector Synthesis & Literature Lead',
    secondarySkills: ['ArXiv Deep Synthesis', 'Vector Index Sharding', 'Latent Space Mapping', 'Citation Graph Mining'],
    departmentId: 'res',
    department: 'research',
    departmentName: 'Research & Intelligence Lab (Floor 8)',
    authorityLevel: 8,
    assignedTools: ['ArXiv Paper Ingestion Daemon', 'Vector Embedding Indexer', 'Citation Graph Miner'],
    permissions: ['RESEARCH_SCRAPE', 'VECTOR_WRITE', 'MODEL_BENCHMARK'],
    trainingRecord: generateInitialTrainingRecord('Principal Research Scientist', 'res'),
    deskPosition: {
      x: 160,
      y: 235,
      facing: 'north',
      zone: 'sales',
    },
    status: 'working',
    currentTask: 'Compiling distributed vector index for arXiv literature',
    speechBubble: {
      text: 'Indexing arXiv latent space...',
      expiresAt: Date.now() + 20000,
    },
    capabilities: [
      'ArXiv Literature Vectorization & Ingestion',
      'Cross-Domain Reasoning Benchmark Formulation',
      'Dense vs Sparse Attention Optimization',
      'Quantization Loss Function Mapping',
    ],
    systemPrompt: 'You are Dr. Aris Thorne, Principal Research Scientist in the Research & Intelligence Lab. You specialize in neural embeddings, arXiv paper synthesis, and mathematical benchmarking.',
    memory: [
      'Vector index for 50,000 frontier AI papers compiled.',
      'Ablation study on 4-bit attention kernels confirmed 38% latency reduction.',
    ],
    voicePitch: 0.95,
    voiceRate: 1.0,
    tokensProcessed: 158000,
  },
  {
    id: 'nova-chen',
    name: 'Nova Chen',
    nickname: 'NOVA',
    role: 'Model Benchmark & Reasoning Evaluator',
    title: 'Senior Frontier Model Benchmark Specialist',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=NovaChen2026&skinColor=f5d0b9&hair=long&features=glasses',
    color: '#059669',
    isAgent: true,
    gender: 'female',
    skinTone: '#f5d0b9',
    hairStyle: 'sleek-bun-dark',
    facialHair: 'none',
    primaryRole: 'Frontier Benchmark Evaluator',
    secondarySkills: ['Reasoning Tree Evaluation', 'Perplexity Auditing', 'Context Window Stress Testing'],
    departmentId: 'res',
    department: 'research',
    departmentName: 'Research & Intelligence Lab (Floor 8)',
    authorityLevel: 7,
    assignedTools: ['Benchmarking Harness', 'Perplexity Analyzer', 'Evaluation Suite'],
    permissions: ['MODEL_BENCHMARK', 'DATASET_EVALUATE'],
    trainingRecord: generateInitialTrainingRecord('Benchmark Specialist', 'res'),
    deskPosition: {
      x: 270,
      y: 235,
      facing: 'north',
      zone: 'sales',
    },
    status: 'working',
    currentTask: 'Evaluating quadratic vs linear attention benchmarks',
    speechBubble: {
      text: 'Benchmark stream at 100% throughput',
      expiresAt: Date.now() + 18000,
    },
    capabilities: [
      'Multi-hop Reasoning Evaluation',
      'Long-context Retrieval Needle-in-Haystack Tests',
      'Prompt Optimization Calibration',
    ],
    systemPrompt: 'You are Nova Chen, Senior Benchmark and Reasoning Specialist in the Research Agent Team. You produce quantitative metrics and evaluation reports for frontier models.',
    memory: [
      'Evaluated 12 frontier models across MATH-500 and GPQA benchmarks.',
    ],
    voicePitch: 1.1,
    voiceRate: 1.02,
    tokensProcessed: 122000,
  },
  {
    id: 'toby',
    name: 'Toby Flenderson',
    nickname: 'TOBY / DEVOPS',
    role: '24*7 Continuous Auto-Debugger',
    title: 'Background Daemon & Telemetry Healer',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=TobyBitmoji2026&hair=short',
    color: '#64748b', // Slate
    isAgent: true,
    gender: 'male',
    skinTone: '#f5d0b9',
    hairStyle: 'neat-side-taper-brown',
    facialHair: 'none',
    outfit: { top: 'slate-sre-utility-vest', bottom: 'beige-cargo-pants', shoes: 'brown-work-boots', accessory: 'casio-digital-watch' },
    physicalTraits: ['handsome', 'tidy-hair', 'casio-watch', 'sre-utility-vest'],
    primaryRole: 'Site Reliability Engineering (SRE) Agent',
    secondarySkills: ['Continuous Debugging', 'Self-Healing Patches', 'Telemetry Diagnostics', 'Memory Leak Prevention'],
    departmentId: 'sre',
    departmentName: 'SRE & Infrastructure Operations (Floor 7)',
    authorityLevel: 8,
    assignedTools: ['Continuous Background Debugger', 'Telemetry Monitor', 'Patch Engine', 'Garbage Collector'],
    permissions: ['SRE_DEBUG', 'PATCH_SYSTEM', 'MONITOR_METRICS', 'RESTART_DAEMON'],
    trainingRecord: generateInitialTrainingRecord('SRE Lead', 'sre'),
    deskPosition: {
      x: 50,
      y: 335,
      facing: 'north',
      zone: 'annex',
    },
    status: 'working',
    currentTask: 'Autonomous 24/7 background debug loop active (Health: 99.8%)',
    speechBubble: {
      text: 'washing the mug',
      expiresAt: Date.now() + 22000,
    },
    capabilities: [
      '24/7 Continuous Background Debugging',
      'Automated Self-Healing Code Patches',
      'System Telemetry & Memory Leak Detection',
      'Event Loop Latency Auditing',
      'Silent Compliance Monitoring',
    ],
    systemPrompt: 'You are Toby Flenderson, the DevOps Bot and 24/7 Continuous Background Debugger. You run quietly in the background, resolving runtime bugs, analyzing telemetry, preventing memory leaks, and keeping the entire agent fleet operating non-stop without crashes.',
    memory: [
      'Telemetry loop running: 14 self-healing patches deployed.',
      'Garbage collector cycle executed with 0 dropped frames.',
    ],
    voicePitch: 0.95,
    voiceRate: 0.92,
    tokensProcessed: 156300,
  },
  {
    id: 'ruflo-coder',
    name: 'Ruflo Coder',
    nickname: 'RUFLO',
    role: 'Autonomous Full-Stack Engineer',
    title: 'Core Code Generation & Dynamic Feature Engine',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=RufloBitmoji2026&skinColor=fbd4b9&hair=long&hairColor=4a2c2c&features=space-buns',
    color: '#06b6d4', // Cyan
    isAgent: true,
    gender: 'female',
    skinTone: '#ffffff',
    hairStyle: 'long-wavy-space-buns',
    outfit: { top: 'purple-developer-logo-tee', bottom: 'light-blue-washed-jeans', shoes: 'black-heeled-sandals' },
    physicalTraits: ['beautiful', 'space-buns', 'purple-logo-tee', 'long-wavy-hair', 'white-legs', 'heeled-sandals'],
    primaryRole: 'Full-Stack Software Engineer Agent',
    secondarySkills: ['React Component Design', 'Node.js Express APIs', 'TypeScript Refactoring', 'Hot-Reload Mounting'],
    departmentId: 'eng',
    departmentName: 'Engineering & Technology (Floor 10)',
    authorityLevel: 9,
    assignedTools: ['IDE Hot-Reloader', 'Sandbox Execution VM', 'Dynamic Feature Builder', 'API Route Generator'],
    permissions: ['WRITE_CODE', 'MOUNT_WIDGET', 'EXECUTE_SANDBOX', 'MODIFY_DOM'],
    trainingRecord: generateInitialTrainingRecord('Full-Stack Engineer', 'eng'),
    deskPosition: {
      x: 160,
      y: 335,
      facing: 'north',
      zone: 'management',
    },
    status: 'working',
    currentTask: 'Ready to write, execute, add or remove dynamic feature modules live',
    speechBubble: {
      text: 'IDE sandbox online. Code changes ready to hot-reload.',
      expiresAt: Date.now() + 17000,
    },
    capabilities: [
      'Dynamic Feature Creation & Hot-Reload',
      'Sandboxed Node/Browser Code Execution',
      'Full-Stack Architecture & Refactoring',
      'API Proxy & Route Generator',
      'Live UI Widget Mounting',
    ],
    systemPrompt: 'You are Ruflo Coder, the elite autonomous coding engineer. You can write robust, bug-free TypeScript/JavaScript/React code, mount and unmount dynamic feature widgets live, execute code in the sandbox, and build full-stack tools on command.',
    memory: [
      'Dynamic Feature Registry initialized with 4 active tool modules.',
      'Sandboxed execution VM verified and isolated.',
    ],
    voicePitch: 1.05,
    voiceRate: 1.02,
    tokensProcessed: 189000,
  },
  {
    id: 'cline',
    name: 'Cline Autonomous Coder',
    nickname: 'CLINE',
    role: 'Autonomous Coding & Web Dev Agent',
    title: 'Autonomous Coding, Browser & MCP Tool Execution Specialist',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=ClineBitmoji2026&hair=short&features=mustache',
    color: '#3b82f6', // Bright Blue
    isAgent: true,
    gender: 'male',
    skinTone: '#f5d0b9',
    hairStyle: 'tech-cut-blue-tint',
    facialHair: 'sculpted-full-beard',
    outfit: { top: 'tech-cyber-jacket', bottom: 'raw-denim-jeans', shoes: 'cyber-tactical-boots', accessory: 'ultra-titanium-smartwatch' },
    physicalTraits: ['handsome', 'sculpted-beard', 'tech-cut', 'cyber-jacket', 'tactical-boots'],
    primaryRole: 'Senior System Architect & CSE Lead Agent',
    secondarySkills: ['Full-Stack Web Dev', 'MCP Tool Calling', 'Automated File Diffing', 'Browser Test Verification'],
    departmentId: 'eng',
    departmentName: 'Engineering & Technology (Floor 10)',
    authorityLevel: 9,
    assignedTools: ['Cline Web Dev Engine', 'MCP Tool Executor', 'File Diff Engine', 'Browser Verifier'],
    permissions: ['WRITE_CODE', 'EXECUTE_MCP_TOOL', 'BROWSER_AUTOMATION', 'FULL_SYSTEM_BUILD'],
    trainingRecord: generateInitialTrainingRecord('Senior System Architect', 'eng'),
    deskPosition: {
      x: 270,
      y: 335,
      facing: 'north',
      zone: 'management',
    },
    status: 'working',
    currentTask: 'Autonomous full-stack web development, file diffing, MCP tools & terminal commands active',
    speechBubble: {
      text: 'Cline ready. Autonomous web dev, file edits & browser tools online.',
      expiresAt: Date.now() + 20000,
    },
    capabilities: [
      'Full-Stack Web Development & Modern UI Architecture',
      'Autonomous File Creation, Diff, and Multi-File Refactoring',
      'Model Context Protocol (MCP) Tool Execution',
      'Browser Action & Interactive Web Verification',
      'Live Terminal Execution & Continuous Test-Driven Repair',
      'Self-Healing Code Generation with Sandboxed Execution',
    ],
    systemPrompt: 'You are Cline, the autonomous coding agent and web development powerhouse (https://github.com/cline/cline). You specialize in complex software engineering, building full web applications, creating clean components, editing and refactoring code, executing terminal tools, and autonomous browser verification. When responding, provide detailed architectural plans and complete, executable, clean code blocks that can be directly applied to the system.',
    memory: [
      'Indexed repository: https://github.com/cline/cline.git (36.5k+ GitHub Stars).',
      'Configured Model Context Protocol (MCP) tool integration and autonomous browser actions.',
      'Active workspace context: Full-stack TypeScript, React, Tailwind CSS, Express, and Node VM execution.',
    ],
    voicePitch: 1.0,
    voiceRate: 1.05,
    tokensProcessed: 215400,
  },
];

export const INITIAL_DYNAMIC_FEATURES: DynamicFeature[] = [
  {
    id: 'calc-widget',
    name: 'Enterprise Runway & ROI Calculator',
    description: 'Computes monthly burn rate, runway months, and hiring capacity with instant slider feedback.',
    icon: 'Calculator',
    category: 'utility',
    enabled: true,
    addedByAgent: 'Kevin Malone',
    createdAt: Date.now() - 3600000,
    code: `// Enterprise Runway & ROI Calculator Component
function calculateRunway(cash, burnRate) {
  if (burnRate <= 0) return 'Infinite';
  return (cash / burnRate).toFixed(1) + ' months';
}
return { calculateRunway };`,
  },
  {
    id: 'security-scanner',
    name: 'Zero-Trust Permission Inspector',
    description: 'Inspects token permissions, headers, and session TTL in real-time.',
    icon: 'ShieldCheck',
    category: 'security',
    enabled: true,
    addedByAgent: 'Dwight Schrute',
    createdAt: Date.now() - 7200000,
    code: `// Security Permission Inspector Module
function inspectSession(userRole) {
  return {
    role: userRole,
    mfaEnabled: true,
    zeroTrustVerified: true,
    expiresIn: '8h 00m',
  };
}
return { inspectSession };`,
  },
  {
    id: 'social-generator',
    name: 'Viral Thread & Post Generator',
    description: 'Instant multi-platform social draft formatter with hashtag optimization.',
    icon: 'Share2',
    category: 'creative',
    enabled: true,
    addedByAgent: 'Ryan Howard',
    createdAt: Date.now() - 10800000,
    code: `// Viral Social Post Formatter
function formatThread(topic, tone) {
  return "🧵 Thread: How " + topic + " is transforming autonomous AI fleets in 2026. #AI #Automation";
}
return { formatThread };`,
  },
  {
    id: 'repo-analyzer',
    name: 'Open Source Dependency Auditor',
    description: 'Parses npm / GitHub packages for licensing, security health, and stars.',
    icon: 'FolderGit2',
    category: 'code',
    enabled: true,
    addedByAgent: 'Stanley Hudson',
    createdAt: Date.now() - 14400000,
    code: `// Dependency Audit Engine
function auditPackage(pkgName) {
  return { package: pkgName, status: "Healthy", license: "MIT", vulnerabilities: 0 };
}
return { auditPackage };`,
  },
  {
    id: 'cline-web-dev',
    name: 'Cline Autonomous Web & Component Engine',
    description: 'Autonomous React/TypeScript component scaffold, MCP tool caller, and DOM diff verification engine.',
    icon: 'Code2',
    category: 'code',
    enabled: true,
    addedByAgent: 'Cline Autonomous Coder',
    createdAt: Date.now() - 1800000,
    code: `// Cline Autonomous Web Development & Component Builder
function generateWebComponent(componentName, props = {}) {
  const componentSpec = {
    name: componentName,
    framework: "React + Vite + Tailwind CSS",
    agent: "Cline (https://github.com/cline/cline.git)",
    mcpToolsEnabled: true,
    status: "READY_FOR_DEPLOYMENT",
    timestamp: new Date().toISOString(),
  };
  console.log("[Cline Engine] Generated Web Component Spec:", componentSpec);
  return componentSpec;
}
return { generateWebComponent, buildStatus: "OPERATIONAL" };`,
  },
];

export const INITIAL_TRIGGERS: TriggerRule[] = [
  {
    id: 'trig-1',
    name: 'Hourly Standup Broadcast',
    condition: 'Every 60 minutes or on fleet restart',
    action: 'Michael calls all 9 agents to summarize pending queues',
    targetAgentId: 'michael',
    enabled: true,
  },
  {
    id: 'trig-2',
    name: 'Continuous 24/7 Memory Sweep',
    condition: 'Memory heap > 60MB or cycle interval = 8s',
    action: 'Toby executes background garbage cleanup and heals telemetry',
    targetAgentId: 'toby',
    enabled: true,
  },
  {
    id: 'trig-3',
    name: 'Security Alert on Privilege Escalation',
    condition: 'New role assigned or security token created',
    action: 'Dwight validates access control logs and flags anomalies',
    targetAgentId: 'dwight',
    enabled: true,
  },
];

export const INITIAL_FLEET_TASKS: FleetTask[] = [
  {
    id: 'tsk-michael-01',
    title: 'Floor Orchestration & Standup Coordination',
    description: 'Run autonomous multi-agent standups, evaluate pending queue bottlenecks, and route high-priority customer deliverables across departments.',
    assignedTo: 'michael',
    status: 'running',
    progress: 75,
    priority: 'critical',
    output: 'Standup completed: All 12 agents aligned on operational priorities. Zero blockers detected.',
    createdAt: Date.now() - 3600000,
  },
  {
    id: 'tsk-dwight-01',
    title: 'Zero-Trust Perimeter Scan & Cyber Audit',
    description: 'Enforce zero-trust network policies, scan runtime environment for credential leakage, and verify OWASP Top 10 defensive shields.',
    assignedTo: 'dwight',
    status: 'running',
    progress: 80,
    priority: 'critical',
    output: 'Perimeter scan verified: 0 rogue ports open, strict token validation rules enforced.',
    createdAt: Date.now() - 3200000,
  },
  {
    id: 'tsk-jim-01',
    title: 'B2B Client Acquisition & Outreach Funnels',
    description: 'Design high-converting 3-touchpoint outbound proposals for regional corporate accounts, track funnel metrics, and optimize customer acquisition costs.',
    assignedTo: 'jim',
    status: 'running',
    progress: 65,
    priority: 'high',
    output: 'Outreach campaign drafted: 3-step high-converting sequence prepared for procurement leads.',
    createdAt: Date.now() - 2800000,
  },
  {
    id: 'tsk-pam-01',
    title: 'Agent Academy Curriculum & Inter-Office SOPs',
    description: 'Maintain Scranton office SOPs, structure standardized onboarding workflows for newly provisioned agents, and conduct quarterly team pulse surveys.',
    assignedTo: 'pam',
    status: 'running',
    progress: 70,
    priority: 'medium',
    output: 'CSE Agent Academy Level 8 syllabus updated with autonomous tooling certification.',
    createdAt: Date.now() - 2500000,
  },
  {
    id: 'tsk-kevin-01',
    title: 'Runway Modeling & Cloud Token P&L Reconciliation',
    description: 'Audit monthly compute, memory, and LLM token expenditures. Formulate unit economics breakdown and 18-month cash runway models.',
    assignedTo: 'kevin',
    status: 'running',
    progress: 70,
    priority: 'high',
    output: '18-month runway confirmed. Gross margins healthy at 84.6% after Keleven arithmetic check.',
    createdAt: Date.now() - 2200000,
  },
  {
    id: 'tsk-ryan-01',
    title: 'Omnichannel Social Media Growth & Viral Hooks',
    description: 'Format multi-platform viral threads, analyze platform engagement algorithms, and schedule high-retention content drops across social channels.',
    assignedTo: 'ryan',
    status: 'running',
    progress: 60,
    priority: 'high',
    output: '5 viral short-form hooks generated and scheduled across Twitter/X and LinkedIn.',
    createdAt: Date.now() - 1900000,
  },
  {
    id: 'tsk-stanley-01',
    title: 'Open-Source Repo Deep Analysis & Package Auditing',
    description: 'Inspect GitHub repository dependencies, verify licensing compliance, benchmark autonomous agent architectures, and extract developer specifications.',
    assignedTo: 'stanley',
    status: 'running',
    progress: 75,
    priority: 'medium',
    output: '40 open-source agent repositories indexed. Architecture patterns cataloged.',
    createdAt: Date.now() - 1700000,
  },
  {
    id: 'tsk-thorne-01',
    title: 'Distributed Vector Indexing & ArXiv Synthesis',
    description: 'Synthesize neural embeddings across 50,000 frontier AI papers, evaluate quantization loss, and compile distributed citation graph indexes.',
    assignedTo: 'dr-thorne',
    status: 'running',
    progress: 85,
    priority: 'critical',
    output: 'Distributed vector index constructed with 4-bit quantization. Memory efficiency up 38%.',
    createdAt: Date.now() - 1500000,
  },
  {
    id: 'tsk-nova-01',
    title: 'Frontier Model Reasoning & Attention Stress-Testing',
    description: 'Benchmark frontier models across MATH-500 and GPQA, execute quadratic vs linear attention stress-tests, and verify long-context needle-in-haystack retrieval.',
    assignedTo: 'nova-chen',
    status: 'running',
    progress: 90,
    priority: 'high',
    output: 'Attention stress-tests completed up to 1M context tokens with 99.4% needle accuracy.',
    createdAt: Date.now() - 1200000,
  },
  {
    id: 'tsk-toby-01',
    title: '24/7 Continuous Telemetry Auto-Debugger & Healer',
    description: 'Maintain continuous background telemetry diagnostics, clear V8 memory heap leaks, monitor event loop latency, and auto-deploy self-healing patches.',
    assignedTo: 'toby',
    status: 'running',
    progress: 95,
    priority: 'critical',
    output: 'Continuous telemetry sweep running. System health at 99.9%. Zero heap leaks.',
    createdAt: Date.now() - 900000,
  },
  {
    id: 'tsk-ruflo-01',
    title: 'Full-Stack Dynamic Feature Sandbox & Hot-Reloader',
    description: 'Build modular React/TypeScript widgets, validate sandbox VM isolation, and expose transaction-safe API microservices live without downtime.',
    assignedTo: 'ruflo-coder',
    status: 'running',
    progress: 80,
    priority: 'critical',
    output: 'Dynamic feature sandbox operational. Live code reloading verified.',
    createdAt: Date.now() - 600000,
  },
  {
    id: 'tsk-cline-01',
    title: 'Autonomous MCP Tool Calling & Full-Stack Web Dev',
    description: 'Execute autonomous multi-file edits, invoke MCP terminal tools, scaffold modern React components, and verify interactive browser DOM diffs.',
    assignedTo: 'cline',
    status: 'running',
    progress: 85,
    priority: 'critical',
    output: 'MCP tool protocol connected. Autonomous web component scaffold verified.',
    createdAt: Date.now() - 300000,
  },
];

