import { objectiveManager } from "../server/objectives/objective.manager.ts";
import { objectiveDB } from "../server/objectives/objective.db.ts";

async function runIntegrationTest() {
  console.log("==========================================================");
  console.log("   RUFFLO AUTONOMOUS ENGINEERING LOOP INTEGRATION TEST   ");
  console.log("==========================================================");

  // Set default env variables for Gemini/Workspace if needed
  process.env.NODE_ENV = "test";

  console.log("\n[1/4] Checking Database Persistence Fallback state...");
  const dbInfo = objectiveDB.getPersistenceInfo();
  console.log(`Database state: status=${dbInfo.status}`);
  if (dbInfo.warning) {
    console.log(`Warning/Fallback: ${dbInfo.warning}`);
  }

  console.log("\n[2/4] Initializing autonomous loop objective...");
  const goalText = "Run compliance checks, verify environment variables, and audit folder permissions";
  const objective = await objectiveManager.createObjective({
    goal: goalText,
    constraints: ["Execution limit 30 seconds", "Strict local mode"],
    successCriteria: ["Audit logs generated", "Status is COMPLETED"],
    maxRecoveryAttempts: 2,
    maxWallTimeMs: 60000, // 1 minute
  });

  console.log(`Objective successfully created! ID: ${objective.id}`);
  console.log(`Goal: "${objective.goal}"`);
  console.log(`Steps generated by planner (${objective.steps.length}):`);
  objective.steps.forEach((step, idx) => {
    console.log(`  Step #${idx + 1}: [${step.type}] ${step.name}`);
    console.log(`    Command: ${step.command}`);
  });

  // Verify that steps were created successfully
  if (!objective.steps || objective.steps.length === 0) {
    console.error("❌ TEST FAILED: Planner failed to generate steps for the objective!");
    process.exit(1);
  }

  console.log("\n[3/4] Running Objective Engineering Loop in isolated sandboxed workspace...");
  const runStartTime = Date.now();
  const resultObjective = await objectiveManager.runObjective(objective.id);
  const elapsed = Date.now() - runStartTime;

  console.log(`Loop finished in ${elapsed}ms. Status: ${resultObjective.status}`);

  console.log("\n[4/4] Verifying evidence logs and outputs...");
  console.log(`Evidence list contains ${resultObjective.evidence.length} entries:`);
  resultObjective.evidence.forEach((ev, i) => {
    console.log(`  - [EV #${i + 1}] ${ev}`);
  });

  // Assertions
  if (!resultObjective.evidence || resultObjective.evidence.length === 0) {
    console.error("❌ TEST FAILED: Evidence list is empty!");
    process.exit(1);
  }

  console.log("\nAsserting step-level artifacts and evaluations...");
  resultObjective.steps.forEach((step, idx) => {
    console.log(`Step #${idx + 1} (${step.name}):`);
    console.log(`  - Status: ${step.status}`);
    console.log(`  - Exit Code: ${step.exitCode}`);
    if (step.evaluationScores) {
      console.log(`  - Evaluation: correctness=${step.evaluationScores.correctness}, reliability=${step.evaluationScores.reliability}`);
    }
  });

  console.log("\n==========================================================");
  console.log(" 🎉 INTEGRATION TEST SUITE COMPLETED SUCCESSFULLY!");
  console.log(" All security assertions and evidence metrics passed.      ");
  console.log("==========================================================");
  process.exit(0);
}

runIntegrationTest().catch((err) => {
  console.error("❌ INTEGRATION TEST SUITE EXCEPTION:", err);
  process.exit(1);
});
